doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            uuid: BGC\Checkout\Shared\Infrastructure\Persistence\DBAL\Types\UuidType
            cart_status: BGC\Checkout\Shared\Infrastructure\Persistence\DBAL\Types\CartStatusType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\MySQLPlatform: identity
        auto_mapping: true
        mappings:
            Shared:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/Persistence/Mapping'
                prefix: 'BGC\Checkout\Shared'
            Carts:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Carts/Infrastructure/Persistence/Mapping'
                prefix: 'BGC\Checkout\Carts'
            Product:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Product/Infrastructure/Persistence/Mapping'
                prefix: 'BGC\Checkout\Product'
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
