cart.create:
  path: /carts
  methods: POST
  controller: BGC\Checkout\Carts\Infrastructure\Controllers\PostCart
  defaults:
    _format: json

cart.item.create:
  path: /carts/{cartId}/items
  methods: POST
  controller: BGC\Checkout\Carts\Infrastructure\Controllers\PostCartItem
  defaults:
    _format: json
  requirements:
    cartId: '[0-9a-f\-]{36}'

cart.get:
  path: /carts/{cartId}
  methods: GET
  controller: BGC\Checkout\Carts\Infrastructure\Controllers\GetCart
  defaults:
    _format: json
  requirements:
    cartId: '[0-9a-f\-]{36}'
