cart.create:
  path: /carts
  methods: POST
  controller: BGC\Checkout\Carts\Infrastructure\Controllers\PostCart
  defaults:
    _format: json

cart.item.create:
  path: /carts/{cartId}/items
  methods: POST
  controller: BGC\Checkout\Carts\Infrastructure\Controllers\PostCartItem
  defaults:
    _format: json
  requirements:
    cartId: '[0-9a-f\-]{36}'

cart.get:
  path: /carts/{cartId}
  methods: GET
  controller: BGC\Checkout\Carts\Infrastructure\Controllers\GetCart
  defaults:
    _format: json
  requirements:
    cartId: '[0-9a-f\-]{36}'

cart.item.modify:
  path: /carts/{cartId}/items/{cartItemId}
  methods: PATCH
  controller: BGC\Checkout\Carts\Infrastructure\Controllers\PatchCartItem
  defaults:
    _format: json
  requirements:
    cartId: '[0-9a-f\-]{36}'
    cartItemId: '[0-9a-f\-]{36}'

cart.item.delete:
  path: /carts/{cartId}/items/{cartItemId}
  methods: DELETE
  controller: BGC\Checkout\Carts\Infrastructure\Controllers\DeleteCartItem
  defaults:
    _format: json
  requirements:
    cartId: '[0-9a-f\-]{36}'
    cartItemId: '[0-9a-f\-]{36}'
